INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (1,1,'In what year did Christopher Columbus first arrive in the Americas?',NULL),
	 (1,2,'Which country was responsible for the construction of the Berlin Wall?',NULL),
	 (1,3,'Who was the first human to journey into space?',NULL),
	 (1,4,'What was the purpose of the Silk Road?',NULL),
	 (1,5,'What war was fought between the North and South regions of the United States?',NULL),
	 (1,6,'Who was the Egyptian queen who ruled from 51-30 BC?',NULL),
	 (1,7,'What was the name of the last imperial dynasty of China?',NULL),
	 (1,8,'In which city was the signing of the Treaty of Versailles?',NULL),
	 (1,9,'Who was the first woman to win a Nobel Prize?',NULL),
	 (1,10,'Which Roman emperor is known for initiating the persecution of Christians?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (2,1,'Who was the first President of the United States?',NULL),
	 (2,2,'What year did the United States declare its independence?',NULL),
	 (2,3,'Which event sparked the beginning of the Civil War?',NULL),
	 (2,4,'Which US President was responsible for the Emancipation Proclamation?',NULL),
	 (2,5,'What was the name of the plan to rebuild Europe after World War II?',NULL),
	 (2,6,'What year did the United States land on the moon?',NULL),
	 (2,7,'Which amendment to the US Constitution abolished slavery?',NULL),
	 (2,8,'Who was the US President during the Cuban Missile Crisis?',NULL),
	 (2,9,'Which movement advocated for equal rights for African Americans in the 1950s-60s?',NULL),
	 (2,10,'What was the purpose of the Lewis and Clark expedition?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (3,1,'Which river was central to the development of ancient Egyptian civilization?',NULL),
	 (3,2,'Which civilization built the city of Machu Picchu?',NULL),
	 (3,3,'What form of writing was used by ancient Sumerians?',NULL),
	 (3,4,'Which ancient civilization was known for their great naval power in the Mediterranean?',NULL),
	 (3,5,'What famous Greek philosopher tutored Alexander the Great?',NULL),
	 (3,6,'What was the capital city of the ancient Roman Empire?',NULL),
	 (3,7,'Which ruler was responsible for unifying ancient China and founding the Qin dynasty?',NULL),
	 (3,8,'What was the main architectural feature of ancient Mesopotamian cities?',NULL),
	 (3,9,'In ancient Greece, which city was known for its military prowess?',NULL),
	 (3,10,'What ancient civilization was centered around the Indus River Valley?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (4,1,'What is the capital of France?',NULL),
	 (4,2,'Which country has the largest land area in the world?',NULL),
	 (4,3,'What is the capital of Australia?',NULL),
	 (4,4,'Which country has the largest population in the world?',NULL),
	 (4,5,'What is the capital of Brazil?',NULL),
	 (4,6,'Which country is known as the Land of the Rising Sun?',NULL),
	 (4,7,'What is the capital of Russia?',NULL),
	 (4,8,'Which African country has the highest population?',NULL),
	 (4,9,'What is the capital of Canada?',NULL),
	 (4,10,'Which country has the most number of official languages?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (5,1,'In which city is the Eiffel Tower located?',NULL),
	 (5,2,'Which country is home to the Great Wall?',NULL),
	 (5,3,'In which city can you find the Statue of Liberty?',NULL),
	 (5,4,'What famous landmark is located in Agra, India?',NULL),
	 (5,5,'Which ancient wonder is located in Giza, Egypt?',NULL),
	 (5,6,'What is the name of the ancient temple complex in Cambodia?',NULL),
	 (5,7,'In which Italian city is the Colosseum located?',NULL),
	 (5,8,'What is the name of the iconic opera house in Sydney, Australia?',NULL),
	 (5,9,'Which South American country has the famous statue called "Christ the Redeemer"?',NULL),
	 (5,10,'In which city is the Tower of London located?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (6,1,'What is the world''s largest desert?',NULL),
	 (6,2,'What is the longest river in the world?',NULL),
	 (6,3,'What is the world''s deepest ocean?',NULL),
	 (6,4,'Which mountain is the tallest in the world?',NULL),
	 (6,5,'Which country has the most number of active volcanoes?',NULL),
	 (6,6,'What is the largest coral reef system in the world?',NULL),
	 (6,7,'What is the name of the world''s largest waterfall system?',NULL),
	 (6,8,'Which continent is the driest in the world?',NULL),
	 (6,9,'What is the largest lake in the world?',NULL),
	 (6,10,'Which country is home to the world''s largest cave system?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (7,1,'What is the basic unit of life?',NULL),
	 (7,2,'What organelle is responsible for producing energy in a cell?',NULL),
	 (7,3,'What is the process by which plants produce food?',NULL),
	 (7,4,'What is the largest organ in the human body?',NULL),
	 (7,5,'What are the building blocks of proteins?',NULL),
	 (7,6,'What is the main component of the cell membrane?',NULL),
	 (7,7,'Which blood cells are responsible for transporting oxygen?',NULL),
	 (7,8,'What is the primary function of DNA?',NULL),
	 (7,9,'What is the process of cell division called?',NULL),
	 (7,10,'Which system in the human body is responsible for breaking down food and absorbing nutrients?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (8,1,'What is the smallest unit of a chemical element?',NULL),
	 (8,2,'What is the name of the chart that organizes all known elements?',NULL),
	 (8,3,'What is the chemical formula for water?',NULL),
	 (8,4,'Which element is the most abundant in the Earth''s atmosphere?',NULL),
	 (8,5,'What is the term for a substance that cannot be broken down into simpler substances?',NULL),
	 (8,6,'What is the name of the bond formed when electrons are shared between atoms?',NULL),
	 (8,7,'What is the atomic number of an element determined by?',NULL),
	 (8,8,'Which element has the chemical symbol "Na"?',NULL),
	 (8,9,'What is the term for the process of a solid turning directly into a gas?',NULL),
	 (8,10,'What is the name of the scale used to measure the acidity or alkalinity of a solution?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (9,1,'What is the force that attracts objects towards each other?',NULL),
	 (9,2,'What is the SI unit of force?',NULL),
	 (9,3,'What is the term for the amount of matter in an object?',NULL),
	 (9,4,'What is the speed of light in a vacuum?',NULL),
	 (9,5,'Which law states that for every action, there is an equal and opposite reaction?',NULL),
	 (9,6,'What is the name for the energy an object possesses due to its motion?',NULL),
	 (9,7,'What is the name for the energy an object possesses due to its position or condition?',NULL),
	 (9,8,'Which scientist is known for developing the theory of general relativity?',NULL),
	 (9,9,'What is the name of the force that opposes the relative motion of two surfaces in contact?',NULL),
	 (9,10,'What is the term for the amount of space an object occupies?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (10,1,'In what year was the University of Southern California founded?',NULL),
	 (10,2,'What is the name of the USC mascot?',NULL),
	 (10,3,'What is the official motto of USC?',NULL),
	 (10,4,'What is the nickname for USC''s athletic teams?',NULL),
	 (10,5,'What was the original name of USC''s School of Cinematic Arts?',NULL),
	 (10,6,'Who was the first president of USC?',NULL),
	 (10,7,'What is the name of the annual football game between USC and UCLA?',NULL),
	 (10,8,'Which well-known entrepreneur and philanthropist donated to create the USC Iovine and Young Academy?',NULL),
	 (10,9,'Which USC building is home to the world''s largest collegiate mural?',NULL),
	 (10,10,'In what year did USC become a member of the Association of American Universities (AAU)?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (11,1,'What is the name of the central plaza on USC''s campus?',NULL),
	 (11,2,'Which USC library is the largest on campus and holds the main collection?',NULL),
	 (11,3,'What is the name of the main dining hall at USC?',NULL),
	 (11,4,'Which campus residence hall is known for its unique architectural design?',NULL),
	 (11,5,'What is the name of the USC Village complex shopping area?',NULL),
	 (11,6,'Which building houses the USC School of Cinematic Arts?',NULL),
	 (11,7,'What is the name of USC''s football stadium?',NULL),
	 (11,8,'Which campus facility serves as the main recreation and fitness center for USC students?',NULL),
	 (11,9,'What is the name of the main auditorium used for large events and guest speakers at USC?',NULL),
	 (11,10,'Which USC building is the home to the School of Architecture?',NULL);
INSERT INTO Question (quiz_id,question_no,description,image_location) VALUES
	 (12,1,'What is the name of the USC men''s basketball team?',NULL),
	 (12,2,'Which USC women''s sports team has won multiple national championships?',NULL),
	 (12,3,'How many NCAA team championships has USC won?',NULL),
	 (12,4,'What is the name of the award given to the most outstanding college football player, won by multiple USC athletes?',NULL),
	 (12,5,'What is the name of the USC football team''s head coach?',NULL),
	 (12,6,'Which USC athlete is a famous American professional tennis player?',NULL),
	 (12,7,'In which sport has USC won the most NCAA championships?',NULL),
	 (12,8,'What is the name of the annual football game between USC and Notre Dame?',NULL),
	 (12,9,'Which USC Olympian is a famous American swimmer who has won multiple gold medals?',NULL),
	 (12,10,'Which USC alumna is a famous American soccer player and two-time Olympic gold medalist?',NULL);
